### PR TITLE
Bump version to fix previous release

### LINKED ISSUE #68: Missing files in redsnow-0.4.2.gem
The released gem file for v0.4.2 is missing the `ext/` folder.

If you look at [the redsnow gem page on rubygems.org](https://rubygems.org/gems/redsnow) it is also clear that something is missing, as the file size is much smaller than usually:

> VERSIONS:
> 0.4.2 - July 7, 2015 (13.5 KB)
> 0.4.1 - April 24, 2015 (8.43 MB)
> 0.4.0 - March 30, 2015 (7.37 MB)
> 0.3.7 - March 25, 2015 (2.59 MB)
> 0.3.4 - December 16, 2014 (3.32 MB)

I've tried building the gem myself and it went fine, so it's probably just a bad build that was pushed.

Since rubygems.org does not allow for re-publishing a gem version, I would suggest yanking v0.4.2 (`gem yank redsnow -v 0.4.2`) and publishing a new version.

### PR DESCRIPTION
**Pull request by abtris**
Fix #68 

I modify travisci to deploy version to rubygems directly. This can be prevent similar problems.

### CODE REVIEW

**Comment by abtris** [comment]
@pksunkara @danielgtaylor Look into this PR. I hope this fix problems with releasing redsnow.

**Comment by danielgtaylor** [comment]
Thanks for the fix!

**Comment by tobiashm** [comment]
This looks awesome. But shouldn't it have been published now? There is a tag, and Github lists the v.0.4.3 release, but [Travis says: “Skipping a deployment with the rubygems provider because this is not a tagged commit”](https://travis-ci.org/apiaryio/redsnow/jobs/70031591) – and it's not on https://rubygems.org/gems/redsnow

**Comment by danielgtaylor** [comment]
@tobiashm seems something is wrong with the tag detection on Travis or we've misconfigured something. Going to try #70 and see if that fixes it.

**Pull request merged**
